#
# チュートリアル: Amazon ECS サービスへのプライベート統合を使用した HTTP API の構築
#
# ステップ 2〜ステップ 5
# https://docs.aws.amazon.com/ja_jp/apigateway/latest/developerguide/http-api-private-integration.html
#
AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Sample ApiGateway

Parameters:
  NetworkStackName:
    Type: String
    Description: Name of mk-ecs-apigw-network Stack
    Default: sample-app-network
  AlbStackName:
    Type: String
    Description: Name of mk-ecs-apigw-alb Stack
    Default: sample-app-alb

Resources:
  # Make VPC Link
  SampleVpcLink:
    Type: AWS::ApiGatewayV2::VpcLink
    Properties:
      Name: "SampleVpcLink"
      SubnetIds:
        - !ImportValue
          'Fn::Sub': "${NetworkStackName}-SampleVPCPrivateSubnet1Subnet"
        - !ImportValue
          'Fn::Sub': "${NetworkStackName}-SampleVPCPrivateSubnet2Subnet"

  # Make Api
  SampleApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: "SampleApi"
      Description: "Sample/ApiGateway"
      ProtocolType: HTTP

  # Make Api Stage
  SampleApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: "$default"
      ApiId: !Ref SampleApi

  # Make Api Integration
  SampleApiIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref SampleApi
      ConnectionId: !Ref SampleVpcLink
      ConnectionType: VPC_LINK
      Description: "SampleApiIntegration"
      IntegrationMethod: ANY
      IntegrationType: HTTP_PROXY
      IntegrationUri: !ImportValue
        'Fn::Sub': "${AlbStackName}-SampleAlbListener"
      PayloadFormatVersion: 1.0

  # Make Api Route
  SampleApiRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref SampleApi
      RouteKey: "ANY /{proxy+}"
      Target: !Sub "integrations/${SampleApiIntegration}"

  # Make Api Deployment
  SampleApiDeployment:
    Type: AWS::ApiGatewayV2::Deployment
    Properties:
      ApiId: !Ref SampleApi
      Description: "SampleApiDeployment"
      StageName: "$default"
    DeletionPolicy: Retain
    DependsOn:
      - SampleApiStage
      - SampleApiRoute

# Outputs
Outputs:
  SampleExternalURL:
    Value: !Sub "${SampleApi}.execute-api.${AWS::Region}.amazonaws.com"
    Export:
      Name: !Sub "${AWS::StackName}-SampleExternalURL"
